{"level":"warn","message":"Created At: 2018-10-27 16:34:06 - DeprecationWarning collection.ensureIndex is deprecated. Use createIndexes instead. DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.\n    at NativeCollection.(anonymous function) [as ensureIndex] (D:\\api-server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:146:28)\n    at NativeCollection.create (D:\\api-server\\node_modules\\mongoose\\lib\\model.js:1384:33)\n    at NativeCollection.Collection.doQueue (D:\\api-server\\node_modules\\mongoose\\lib\\collection.js:124:24)\n    at immediate (D:\\api-server\\node_modules\\mongoose\\lib\\collection.js:86:24)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-12 17:57:48 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"warn","message":"Created At: 2018-11-12 17:59:55 - DeprecationWarning collection.ensureIndex is deprecated. Use createIndexes instead. DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.\n    at NativeCollection.(anonymous function) [as ensureIndex] (D:\\api-server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:146:28)\n    at NativeCollection.create (D:\\api-server\\node_modules\\mongoose\\lib\\model.js:1384:33)\n    at NativeCollection.Collection.doQueue (D:\\api-server\\node_modules\\mongoose\\lib\\collection.js:124:24)\n    at immediate (D:\\api-server\\node_modules\\mongoose\\lib\\collection.js:86:24)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"warn","message":"Created At: 2018-11-12 18:03:35 - DeprecationWarning collection.ensureIndex is deprecated. Use createIndexes instead. DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.\n    at NativeCollection.(anonymous function) [as ensureIndex] (D:\\api-server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:146:28)\n    at NativeCollection.create (D:\\api-server\\node_modules\\mongoose\\lib\\model.js:1384:33)\n    at NativeCollection.Collection.doQueue (D:\\api-server\\node_modules\\mongoose\\lib\\collection.js:124:24)\n    at immediate (D:\\api-server\\node_modules\\mongoose\\lib\\collection.js:86:24)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-12 18:13:11 - ForbiddenError: invalid csrf token\n    at csrf (D:\\api-server\\node_modules\\csurf\\index.js:112:19)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:14:35 - ForbiddenError: invalid csrf token\n    at csrf (D:\\api-server\\node_modules\\csurf\\index.js:112:19)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at urlencodedParser (D:\\api-server\\node_modules\\body-parser\\lib\\types\\urlencoded.js:100:7)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7"}
{"level":"error","message":"Created At: 2018-11-12 18:23:45 - ForbiddenError: invalid csrf token\n    at csrf (D:\\api-server\\node_modules\\csurf\\index.js:112:19)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:34:18 - ForbiddenError: invalid csrf token\n    at csrf (D:\\api-server\\node_modules\\csurf\\index.js:112:19)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:56:14)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:35:07 - ForbiddenError: invalid csrf token\n    at csrf (D:\\api-server\\node_modules\\csurf\\index.js:112:19)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:56:14)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:36:56 - ForbiddenError: invalid csrf token\n    at csrf (D:\\api-server\\node_modules\\csurf\\index.js:112:19)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)"}
{"level":"error","message":"Created At: 2018-11-12 18:37:58 - ForbiddenError: invalid csrf token\n    at csrf (D:\\api-server\\node_modules\\csurf\\index.js:112:19)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)"}
{"level":"error","message":"Created At: 2018-11-12 18:39:18 - ForbiddenError: invalid csrf token\n    at csrf (D:\\api-server\\node_modules\\csurf\\index.js:112:19)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:41:46 - TypeError: req.csrfToken is not a function\n    at D:\\api-server\\routes\\signup.js:40:16\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:41:47 - TypeError: req.csrfToken is not a function\n    at D:\\api-server\\routes\\signup.js:40:16\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:42:07 - ForbiddenError: invalid csrf token\n    at csrf (D:\\api-server\\node_modules\\csurf\\index.js:112:19)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:42:21 - TypeError: req.csrfToken is not a function\n    at D:\\api-server\\routes\\signup.js:40:16\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:42:43 - TypeError: req.csrfToken is not a function\n    at D:\\api-server\\routes\\signup.js:40:16\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:43:22 - TypeError: req.csrfToken is not a function\n    at D:\\api-server\\routes\\signup.js:40:16\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:43:27 - TypeError: req.csrfToken is not a function\n    at D:\\api-server\\routes\\signup.js:40:16\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:43:30 - TypeError: req.csrfToken is not a function\n    at D:\\api-server\\routes\\signup.js:40:16\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:43:33 - TypeError: req.csrfToken is not a function\n    at D:\\api-server\\routes\\signup.js:40:16\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:43:41 - TypeError: req.csrfToken is not a function\n    at D:\\api-server\\routes\\signup.js:40:16\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-12 18:44:56 - ForbiddenError: invalid csrf token\n    at csrf (D:\\api-server\\node_modules\\csurf\\index.js:112:19)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at cookieParser (D:\\api-server\\node_modules\\cookie-parser\\index.js:70:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)"}
{"level":"error","message":"Created At: 2018-11-14 13:40:51 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:42:08 - ReferenceError: request is not defined\n    at signup.get (D:\\api-server\\routes\\signup.js:40:2)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at param (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:354:14)\n    at param (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:410:3)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)"}
{"level":"error","message":"Created At: 2018-11-14 13:46:08 - ReferenceError: request is not defined\n    at signup.get (D:\\api-server\\routes\\signup.js:40:2)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at param (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:354:14)\n    at param (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:410:3)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)"}
{"level":"error","message":"Created At: 2018-11-14 13:46:46 - ReferenceError: request is not defined\n    at signup.get (D:\\api-server\\routes\\signup.js:40:2)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at param (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:354:14)\n    at param (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:410:3)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)"}
{"level":"error","message":"Created At: 2018-11-14 13:46:46 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:47:00 - ReferenceError: request is not defined\n    at signup.get (D:\\api-server\\routes\\signup.js:40:2)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (D:\\api-server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at param (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:354:14)\n    at param (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:410:3)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (D:\\api-server\\node_modules\\morgan\\index.js:144:5)\n    at Layer.handle [as handle_request] (D:\\api-server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at D:\\api-server\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (D:\\api-server\\node_modules\\express\\lib\\router\\index.js:335:12)"}
{"level":"error","message":"Created At: 2018-11-14 13:48:01 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:49:48 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:50:12 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:50:47 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:50:54 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:51:29 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:51:33 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:54:44 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:55:59 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:56:41 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:56:55 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 13:57:39 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:00:33 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:01:12 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:01:25 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:02:09 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:03:34 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:04:49 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:05:33 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:06:18 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:07:42 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:08:28 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:08:40 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:09:14 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:10:42 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:10:54 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:12:10 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:14:10 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:15:05 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:15:38 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:15:51 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:16:43 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:16:59 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:17:28 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:17:44 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:18:09 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:18:35 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:20:22 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:38:53 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:39:24 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 14:39:49 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:37:22 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:38:34 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:39:18 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:39:24 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:39:55 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:44:26 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:46:01 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:46:17 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:46:37 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:48:08 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:49:37 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:49:42 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:50:26 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:51:23 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:51:37 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 15:51:47 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:01:25 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:02:28 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:03:14 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:03:40 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:03:57 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:05:07 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:05:26 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:06:37 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:07:32 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:08:09 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:09:13 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:09:22 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:10:43 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:13:26 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:14:51 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:18:36 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:20:31 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:58:01 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:58:16 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 16:59:03 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 17:00:50 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 17:01:22 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 17:44:22 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-14 17:45:10 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-21 14:52:05 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:09:02 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:09:33 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:10:15 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:10:39 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:11:02 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:11:19 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:12:33 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:12:41 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:14:03 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:14:18 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:15:28 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:15:40 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:16:54 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:17:11 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:18:12 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:19:22 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:20:12 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:20:39 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:20:44 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:22:04 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:22:12 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:22:28 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:24:28 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:26:16 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:26:20 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:26:23 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:26:30 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:26:52 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:28:11 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:28:18 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:29:05 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:29:12 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:29:20 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:29:31 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:30:00 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:30:33 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:30:41 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:31:31 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:32:14 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 12:33:21 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 18:44:26 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 18:44:35 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 18:45:50 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 18:47:08 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 2018-11-26 18:47:24 - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}
{"level":"error","message":"Created At: 11/26/2018, 7:18:01 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/26/2018, 7:26:43 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/28/2018, 3:33:23 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/28/2018, 3:37:23 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/28/2018, 3:38:06 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/28/2018, 3:39:29 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/28/2018, 4:30:34 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/28/2018, 4:36:41 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/28/2018, 4:39:58 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (d:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (d:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (d:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/28/2018, 4:41:09 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (d:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (d:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (d:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/28/2018, 4:41:29 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (d:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (d:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (d:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/28/2018, 4:46:33 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"level":"error","message":"Created At: 11/28/2018, 4:47:00 PM - MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (D:\\api-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
